# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\upload.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName(_fromUtf8("StackedWidget"))
        StackedWidget.resize(791, 605)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        StackedWidget.setFont(font)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 741, 571))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.progressBox = QtGui.QGroupBox(self.groupBox)
        self.progressBox.setGeometry(QtCore.QRect(20, 420, 161, 101))
        self.progressBox.setTitle(_fromUtf8(""))
        self.progressBox.setObjectName(_fromUtf8("progressBox"))
        self.nextLabel = QtGui.QLabel(self.progressBox)
        self.nextLabel.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.nextLabel.setFont(font)
        self.nextLabel.setAutoFillBackground(False)
        self.nextLabel.setObjectName(_fromUtf8("nextLabel"))
        self.nextBtn = QtGui.QPushButton(self.progressBox)
        self.nextBtn.setGeometry(QtCore.QRect(10, 40, 141, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.nextBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/next/Hopstarter-Button-Button-Next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextBtn.setIcon(icon)
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.seedBox = QtGui.QGroupBox(self.groupBox)
        self.seedBox.setGeometry(QtCore.QRect(40, 30, 661, 141))
        self.seedBox.setObjectName(_fromUtf8("seedBox"))
        self.seedTagTextBox = QtGui.QLineEdit(self.seedBox)
        self.seedTagTextBox.setGeometry(QtCore.QRect(22, 79, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.seedTagTextBox.setFont(font)
        self.seedTagTextBox.setObjectName(_fromUtf8("seedTagTextBox"))
        self.label = QtGui.QLabel(self.seedBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.seedTagBtn = QtGui.QPushButton(self.seedBox)
        self.seedTagBtn.setGeometry(QtCore.QRect(170, 72, 131, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/info/Hopstarter-Button-Button-Info.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.seedTagBtn.setIcon(icon1)
        self.seedTagBtn.setObjectName(_fromUtf8("seedTagBtn"))
        self.tagsBox = QtGui.QGroupBox(self.groupBox)
        self.tagsBox.setGeometry(QtCore.QRect(40, 180, 661, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.tagsBox.setFont(font)
        self.tagsBox.setObjectName(_fromUtf8("tagsBox"))
        self.textEdit = QtGui.QTextEdit(self.tagsBox)
        self.textEdit.setGeometry(QtCore.QRect(30, 40, 351, 51))
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_2 = QtGui.QLabel(self.tagsBox)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 251, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        StackedWidget.addWidget(self.page)
        self.page1 = QtGui.QWidget()
        self.page1.setObjectName(_fromUtf8("page1"))
        self.uploadBox = QtGui.QGroupBox(self.page1)
        self.uploadBox.setGeometry(QtCore.QRect(40, 40, 681, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.uploadBox.setFont(font)
        self.uploadBox.setObjectName(_fromUtf8("uploadBox"))
        self.splitter = QtGui.QSplitter(self.uploadBox)
        self.splitter.setGeometry(QtCore.QRect(50, 40, 571, 161))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.youtubeBtn = QtGui.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.youtubeBtn.setFont(font)
        self.youtubeBtn.setObjectName(_fromUtf8("youtubeBtn"))
        self.vimeoBtn = QtGui.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.vimeoBtn.setFont(font)
        self.vimeoBtn.setObjectName(_fromUtf8("vimeoBtn"))
        self.progressBox_2 = QtGui.QGroupBox(self.page1)
        self.progressBox_2.setGeometry(QtCore.QRect(20, 430, 161, 101))
        self.progressBox_2.setTitle(_fromUtf8(""))
        self.progressBox_2.setObjectName(_fromUtf8("progressBox_2"))
        self.nextLabel_2 = QtGui.QLabel(self.progressBox_2)
        self.nextLabel_2.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.nextLabel_2.setFont(font)
        self.nextLabel_2.setAutoFillBackground(False)
        self.nextLabel_2.setObjectName(_fromUtf8("nextLabel_2"))
        self.finishBtn = QtGui.QPushButton(self.progressBox_2)
        self.finishBtn.setGeometry(QtCore.QRect(10, 40, 141, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.finishBtn.setFont(font)
        self.finishBtn.setIcon(icon)
        self.finishBtn.setObjectName(_fromUtf8("finishBtn"))
        StackedWidget.addWidget(self.page1)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(_translate("StackedWidget", "Video Venom", None))
        self.groupBox.setTitle(_translate("StackedWidget", "Generate tags for videos", None))
        self.nextLabel.setText(_translate("StackedWidget", "Step 4/5", None))
        self.nextBtn.setText(_translate("StackedWidget", "Select video sites", None))
        self.seedBox.setTitle(_translate("StackedWidget", "Seed Tag", None))
        self.label.setText(_translate("StackedWidget", "Enter seed tag to generate multiple tags", None))
        self.seedTagBtn.setText(_translate("StackedWidget", "Generate Tags", None))
        self.tagsBox.setTitle(_translate("StackedWidget", "Generated and Custom Tags", None))
        self.label_2.setText(_translate("StackedWidget", "Tags (Powered by Youtube suggestions)", None))
        self.uploadBox.setTitle(_translate("StackedWidget", "Authenticate to video sharing sites", None))
        self.youtubeBtn.setText(_translate("StackedWidget", "Youtube", None))
        self.vimeoBtn.setText(_translate("StackedWidget", "Vimeo", None))
        self.nextLabel_2.setText(_translate("StackedWidget", "Step 5/5", None))
        self.finishBtn.setText(_translate("StackedWidget", "Finish and upload", None))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    StackedWidget = QtGui.QStackedWidget()
    ui = Ui_StackedWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())

