# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wizard.ui'
#
# Created: Thu May 12 19:55:12 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName(_fromUtf8("StackedWidget"))
        StackedWidget.resize(874, 894)
        self.welcomePage = QtGui.QWidget()
        self.welcomePage.setObjectName(_fromUtf8("welcomePage"))
        self.bannerGroup = QtGui.QGroupBox(self.welcomePage)
        self.bannerGroup.setGeometry(QtCore.QRect(10, 10, 821, 141))
        self.bannerGroup.setObjectName(_fromUtf8("bannerGroup"))
        self.bgLabel = QtGui.QLabel(self.bannerGroup)
        self.bgLabel.setGeometry(QtCore.QRect(10, 30, 811, 81))
        self.bgLabel.setStyleSheet(_fromUtf8(""))
        self.bgLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.bgLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.bgLabel.setText(_fromUtf8(""))
        self.bgLabel.setObjectName(_fromUtf8("bgLabel"))
        self.mainGroup = QtGui.QGroupBox(self.welcomePage)
        self.mainGroup.setGeometry(QtCore.QRect(10, 150, 821, 621))
        self.mainGroup.setObjectName(_fromUtf8("mainGroup"))
        self.buttonGroup = QtGui.QGroupBox(self.welcomePage)
        self.buttonGroup.setGeometry(QtCore.QRect(580, 810, 261, 80))
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.widget = QtGui.QWidget(self.buttonGroup)
        self.widget.setGeometry(QtCore.QRect(7, 30, 251, 28))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.prevButton = QtGui.QPushButton(self.widget)
        self.prevButton.setObjectName(_fromUtf8("prevButton"))
        self.horizontalLayout.addWidget(self.prevButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.nextButton = QtGui.QPushButton(self.widget)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout.addWidget(self.nextButton)
        StackedWidget.addWidget(self.welcomePage)
        self.videoLoadPage = QtGui.QWidget()
        self.videoLoadPage.setObjectName(_fromUtf8("videoLoadPage"))
        self.bannerGroup_2 = QtGui.QGroupBox(self.videoLoadPage)
        self.bannerGroup_2.setGeometry(QtCore.QRect(10, 10, 821, 141))
        self.bannerGroup_2.setObjectName(_fromUtf8("bannerGroup_2"))
        self.bgLabel_4 = QtGui.QLabel(self.bannerGroup_2)
        self.bgLabel_4.setGeometry(QtCore.QRect(10, 30, 811, 81))
        self.bgLabel_4.setStyleSheet(_fromUtf8(""))
        self.bgLabel_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.bgLabel_4.setFrameShadow(QtGui.QFrame.Plain)
        self.bgLabel_4.setText(_fromUtf8(""))
        self.bgLabel_4.setObjectName(_fromUtf8("bgLabel_4"))
        self.buttonGroup_2 = QtGui.QGroupBox(self.videoLoadPage)
        self.buttonGroup_2.setGeometry(QtCore.QRect(580, 810, 261, 80))
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.layoutWidget_3 = QtGui.QWidget(self.buttonGroup_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(7, 30, 251, 28))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.prevButton_4 = QtGui.QPushButton(self.layoutWidget_3)
        self.prevButton_4.setObjectName(_fromUtf8("prevButton_4"))
        self.horizontalLayout_4.addWidget(self.prevButton_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.nextButton_4 = QtGui.QPushButton(self.layoutWidget_3)
        self.nextButton_4.setObjectName(_fromUtf8("nextButton_4"))
        self.horizontalLayout_4.addWidget(self.nextButton_4)
        self.mainGroup_2 = QtGui.QGroupBox(self.videoLoadPage)
        self.mainGroup_2.setGeometry(QtCore.QRect(10, 150, 821, 621))
        self.mainGroup_2.setObjectName(_fromUtf8("mainGroup_2"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.mainGroup_2)
        self.volumeSlider.setGeometry(QtCore.QRect(610, 340, 109, 31))
        self.volumeSlider.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0)"))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.videoPlayer = phonon.Phonon.VideoPlayer(self.mainGroup_2)
        self.videoPlayer.setGeometry(QtCore.QRect(51, 41, 671, 281))
        self.videoPlayer.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 100)"))
        self.videoPlayer.setObjectName(_fromUtf8("videoPlayer"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.mainGroup_2)
        self.seekSlider.setGeometry(QtCore.QRect(60, 400, 661, 20))
        self.seekSlider.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0)"))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.layoutWidget_9 = QtGui.QWidget(self.mainGroup_2)
        self.layoutWidget_9.setGeometry(QtCore.QRect(190, 420, 411, 81))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.playButton = QtGui.QPushButton(self.layoutWidget_9)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_10.addWidget(self.playButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.pauseButton = QtGui.QPushButton(self.layoutWidget_9)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.horizontalLayout_10.addWidget(self.pauseButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.stopButton = QtGui.QPushButton(self.layoutWidget_9)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_10.addWidget(self.stopButton)
        StackedWidget.addWidget(self.videoLoadPage)
        self.bannerPage = QtGui.QWidget()
        self.bannerPage.setObjectName(_fromUtf8("bannerPage"))
        self.bannerGroup_3 = QtGui.QGroupBox(self.bannerPage)
        self.bannerGroup_3.setGeometry(QtCore.QRect(10, 10, 821, 141))
        self.bannerGroup_3.setObjectName(_fromUtf8("bannerGroup_3"))
        self.bgLabel_5 = QtGui.QLabel(self.bannerGroup_3)
        self.bgLabel_5.setGeometry(QtCore.QRect(10, 30, 811, 81))
        self.bgLabel_5.setStyleSheet(_fromUtf8(""))
        self.bgLabel_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.bgLabel_5.setFrameShadow(QtGui.QFrame.Plain)
        self.bgLabel_5.setText(_fromUtf8(""))
        self.bgLabel_5.setObjectName(_fromUtf8("bgLabel_5"))
        self.buttonGroup_3 = QtGui.QGroupBox(self.bannerPage)
        self.buttonGroup_3.setGeometry(QtCore.QRect(580, 810, 261, 80))
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.layoutWidget_4 = QtGui.QWidget(self.buttonGroup_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(7, 30, 251, 28))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.prevButton_5 = QtGui.QPushButton(self.layoutWidget_4)
        self.prevButton_5.setObjectName(_fromUtf8("prevButton_5"))
        self.horizontalLayout_5.addWidget(self.prevButton_5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.nextButton_5 = QtGui.QPushButton(self.layoutWidget_4)
        self.nextButton_5.setObjectName(_fromUtf8("nextButton_5"))
        self.horizontalLayout_5.addWidget(self.nextButton_5)
        self.mainGroup_3 = QtGui.QGroupBox(self.bannerPage)
        self.mainGroup_3.setGeometry(QtCore.QRect(10, 150, 821, 621))
        self.mainGroup_3.setObjectName(_fromUtf8("mainGroup_3"))
        self.layoutWidget_10 = QtGui.QWidget(self.mainGroup_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(51, 312, 731, 81))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.textLabel = QtGui.QLabel(self.layoutWidget_10)
        self.textLabel.setObjectName(_fromUtf8("textLabel"))
        self.horizontalLayout_11.addWidget(self.textLabel)
        self.bannerText = QtGui.QLineEdit(self.layoutWidget_10)
        self.bannerText.setObjectName(_fromUtf8("bannerText"))
        self.horizontalLayout_11.addWidget(self.bannerText)
        self.frame = QtGui.QLabel(self.mainGroup_3)
        self.frame.setGeometry(QtCore.QRect(59, 40, 721, 201))
        self.frame.setMouseTracking(False)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 100)"))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setText(_fromUtf8(""))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.bannerLabel = QtGui.QLabel(self.mainGroup_3)
        self.bannerLabel.setGeometry(QtCore.QRect(109, 190, 231, 31))
        self.bannerLabel.setAutoFillBackground(False)
        self.bannerLabel.setStyleSheet(_fromUtf8("background-color: rgba(200, 240, 240, 100)"))
        self.bannerLabel.setFrameShape(QtGui.QFrame.Box)
        self.bannerLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.bannerLabel.setObjectName(_fromUtf8("bannerLabel"))
        self.bannerBtn = QtGui.QPushButton(self.mainGroup_3)
        self.bannerBtn.setGeometry(QtCore.QRect(51, 261, 731, 31))
        self.bannerBtn.setObjectName(_fromUtf8("bannerBtn"))
        self.previewBtn = QtGui.QPushButton(self.mainGroup_3)
        self.previewBtn.setGeometry(QtCore.QRect(690, 560, 91, 31))
        self.previewBtn.setObjectName(_fromUtf8("previewBtn"))
        self.widget1 = QtGui.QWidget(self.mainGroup_3)
        self.widget1.setGeometry(QtCore.QRect(51, 427, 731, 111))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fontBtn = QtGui.QPushButton(self.widget1)
        self.fontBtn.setObjectName(_fromUtf8("fontBtn"))
        self.gridLayout.addWidget(self.fontBtn, 0, 0, 1, 1)
        self.colorBtn = QtGui.QPushButton(self.widget1)
        self.colorBtn.setObjectName(_fromUtf8("colorBtn"))
        self.gridLayout.addWidget(self.colorBtn, 0, 1, 1, 1)
        StackedWidget.addWidget(self.bannerPage)
        self.timelinePage = QtGui.QWidget()
        self.timelinePage.setObjectName(_fromUtf8("timelinePage"))
        self.bannerGroup_4 = QtGui.QGroupBox(self.timelinePage)
        self.bannerGroup_4.setGeometry(QtCore.QRect(10, 10, 821, 141))
        self.bannerGroup_4.setObjectName(_fromUtf8("bannerGroup_4"))
        self.bgLabel_6 = QtGui.QLabel(self.bannerGroup_4)
        self.bgLabel_6.setGeometry(QtCore.QRect(10, 30, 811, 81))
        self.bgLabel_6.setStyleSheet(_fromUtf8(""))
        self.bgLabel_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.bgLabel_6.setFrameShadow(QtGui.QFrame.Plain)
        self.bgLabel_6.setText(_fromUtf8(""))
        self.bgLabel_6.setObjectName(_fromUtf8("bgLabel_6"))
        self.buttonGroup_4 = QtGui.QGroupBox(self.timelinePage)
        self.buttonGroup_4.setGeometry(QtCore.QRect(580, 810, 261, 80))
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.layoutWidget_5 = QtGui.QWidget(self.buttonGroup_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(7, 30, 251, 28))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.prevButton_6 = QtGui.QPushButton(self.layoutWidget_5)
        self.prevButton_6.setObjectName(_fromUtf8("prevButton_6"))
        self.horizontalLayout_6.addWidget(self.prevButton_6)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.nextButton_6 = QtGui.QPushButton(self.layoutWidget_5)
        self.nextButton_6.setObjectName(_fromUtf8("nextButton_6"))
        self.horizontalLayout_6.addWidget(self.nextButton_6)
        self.mainGroup_4 = QtGui.QGroupBox(self.timelinePage)
        self.mainGroup_4.setGeometry(QtCore.QRect(10, 150, 821, 621))
        self.mainGroup_4.setObjectName(_fromUtf8("mainGroup_4"))
        self.seekSlider_2 = phonon.Phonon.SeekSlider(self.mainGroup_4)
        self.seekSlider_2.setGeometry(QtCore.QRect(39, 389, 661, 20))
        self.seekSlider_2.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0)"))
        self.seekSlider_2.setObjectName(_fromUtf8("seekSlider_2"))
        self.layoutWidget_11 = QtGui.QWidget(self.mainGroup_4)
        self.layoutWidget_11.setGeometry(QtCore.QRect(169, 409, 411, 81))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.playButton_2 = QtGui.QPushButton(self.layoutWidget_11)
        self.playButton_2.setObjectName(_fromUtf8("playButton_2"))
        self.horizontalLayout_12.addWidget(self.playButton_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.pauseButton_2 = QtGui.QPushButton(self.layoutWidget_11)
        self.pauseButton_2.setObjectName(_fromUtf8("pauseButton_2"))
        self.horizontalLayout_12.addWidget(self.pauseButton_2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.stopButton_2 = QtGui.QPushButton(self.layoutWidget_11)
        self.stopButton_2.setObjectName(_fromUtf8("stopButton_2"))
        self.horizontalLayout_12.addWidget(self.stopButton_2)
        self.volumeSlider_2 = phonon.Phonon.VolumeSlider(self.mainGroup_4)
        self.volumeSlider_2.setGeometry(QtCore.QRect(589, 329, 109, 31))
        self.volumeSlider_2.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0)"))
        self.volumeSlider_2.setObjectName(_fromUtf8("volumeSlider_2"))
        self.videoPlayer_2 = phonon.Phonon.VideoPlayer(self.mainGroup_4)
        self.videoPlayer_2.setGeometry(QtCore.QRect(30, 30, 671, 281))
        self.videoPlayer_2.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 100)"))
        self.videoPlayer_2.setObjectName(_fromUtf8("videoPlayer_2"))
        self.startTimeLabel = QtGui.QLabel(self.mainGroup_4)
        self.startTimeLabel.setGeometry(QtCore.QRect(610, 395, 61, 21))
        self.startTimeLabel.setObjectName(_fromUtf8("startTimeLabel"))
        self.startTimeWidget = QtGui.QTimeEdit(self.mainGroup_4)
        self.startTimeWidget.setGeometry(QtCore.QRect(610, 420, 121, 21))
        self.startTimeWidget.setObjectName(_fromUtf8("startTimeWidget"))
        self.startTimeLabel_2 = QtGui.QLabel(self.mainGroup_4)
        self.startTimeLabel_2.setGeometry(QtCore.QRect(610, 450, 61, 16))
        self.startTimeLabel_2.setObjectName(_fromUtf8("startTimeLabel_2"))
        self.endTimeWidget = QtGui.QTimeEdit(self.mainGroup_4)
        self.endTimeWidget.setGeometry(QtCore.QRect(610, 470, 121, 21))
        self.endTimeWidget.setObjectName(_fromUtf8("endTimeWidget"))
        StackedWidget.addWidget(self.timelinePage)
        self.tagPage = QtGui.QWidget()
        self.tagPage.setObjectName(_fromUtf8("tagPage"))
        self.bannerGroup_5 = QtGui.QGroupBox(self.tagPage)
        self.bannerGroup_5.setGeometry(QtCore.QRect(10, 10, 821, 141))
        self.bannerGroup_5.setObjectName(_fromUtf8("bannerGroup_5"))
        self.bgLabel_7 = QtGui.QLabel(self.bannerGroup_5)
        self.bgLabel_7.setGeometry(QtCore.QRect(10, 30, 811, 81))
        self.bgLabel_7.setStyleSheet(_fromUtf8(""))
        self.bgLabel_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.bgLabel_7.setFrameShadow(QtGui.QFrame.Plain)
        self.bgLabel_7.setText(_fromUtf8(""))
        self.bgLabel_7.setObjectName(_fromUtf8("bgLabel_7"))
        self.mainGroup_5 = QtGui.QGroupBox(self.tagPage)
        self.mainGroup_5.setGeometry(QtCore.QRect(10, 150, 821, 621))
        self.mainGroup_5.setObjectName(_fromUtf8("mainGroup_5"))
        self.widget2 = QtGui.QWidget(self.mainGroup_5)
        self.widget2.setGeometry(QtCore.QRect(40, 70, 681, 461))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.seedBox = QtGui.QGroupBox(self.widget2)
        self.seedBox.setObjectName(_fromUtf8("seedBox"))
        self.seedTagTextBox = QtGui.QLineEdit(self.seedBox)
        self.seedTagTextBox.setGeometry(QtCore.QRect(30, 80, 211, 21))
        self.seedTagTextBox.setObjectName(_fromUtf8("seedTagTextBox"))
        self.label = QtGui.QLabel(self.seedBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 211, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.seedTagBtn = QtGui.QPushButton(self.seedBox)
        self.seedTagBtn.setGeometry(QtCore.QRect(260, 72, 111, 31))
        self.seedTagBtn.setObjectName(_fromUtf8("seedTagBtn"))
        self.verticalLayout.addWidget(self.seedBox)
        self.tagsBox = QtGui.QGroupBox(self.widget2)
        self.tagsBox.setObjectName(_fromUtf8("tagsBox"))
        self.textEdit = QtGui.QTextEdit(self.tagsBox)
        self.textEdit.setGeometry(QtCore.QRect(30, 40, 351, 51))
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_2 = QtGui.QLabel(self.tagsBox)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 251, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.tagsBox)
        self.buttonGroup_5 = QtGui.QGroupBox(self.tagPage)
        self.buttonGroup_5.setGeometry(QtCore.QRect(580, 810, 261, 80))
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.layoutWidget_6 = QtGui.QWidget(self.buttonGroup_5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(7, 30, 251, 28))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.prevButton_7 = QtGui.QPushButton(self.layoutWidget_6)
        self.prevButton_7.setObjectName(_fromUtf8("prevButton_7"))
        self.horizontalLayout_7.addWidget(self.prevButton_7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.nextButton_7 = QtGui.QPushButton(self.layoutWidget_6)
        self.nextButton_7.setObjectName(_fromUtf8("nextButton_7"))
        self.horizontalLayout_7.addWidget(self.nextButton_7)
        StackedWidget.addWidget(self.tagPage)
        self.authPage = QtGui.QWidget()
        self.authPage.setObjectName(_fromUtf8("authPage"))
        self.bannerGroup_6 = QtGui.QGroupBox(self.authPage)
        self.bannerGroup_6.setGeometry(QtCore.QRect(10, 10, 821, 141))
        self.bannerGroup_6.setObjectName(_fromUtf8("bannerGroup_6"))
        self.bgLabel_8 = QtGui.QLabel(self.bannerGroup_6)
        self.bgLabel_8.setGeometry(QtCore.QRect(10, 30, 811, 81))
        self.bgLabel_8.setStyleSheet(_fromUtf8(""))
        self.bgLabel_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.bgLabel_8.setFrameShadow(QtGui.QFrame.Plain)
        self.bgLabel_8.setText(_fromUtf8(""))
        self.bgLabel_8.setObjectName(_fromUtf8("bgLabel_8"))
        self.mainGroup_6 = QtGui.QGroupBox(self.authPage)
        self.mainGroup_6.setGeometry(QtCore.QRect(10, 150, 821, 621))
        self.mainGroup_6.setObjectName(_fromUtf8("mainGroup_6"))
        self.uploadBox = QtGui.QGroupBox(self.mainGroup_6)
        self.uploadBox.setGeometry(QtCore.QRect(70, 80, 581, 431))
        self.uploadBox.setObjectName(_fromUtf8("uploadBox"))
        self.youtubeBtn = QtGui.QPushButton(self.uploadBox)
        self.youtubeBtn.setGeometry(QtCore.QRect(50, 40, 121, 91))
        self.youtubeBtn.setObjectName(_fromUtf8("youtubeBtn"))
        self.vimeoBtn = QtGui.QPushButton(self.uploadBox)
        self.vimeoBtn.setGeometry(QtCore.QRect(350, 40, 121, 91))
        self.vimeoBtn.setObjectName(_fromUtf8("vimeoBtn"))
        self.buttonGroup_6 = QtGui.QGroupBox(self.authPage)
        self.buttonGroup_6.setGeometry(QtCore.QRect(580, 810, 261, 80))
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.layoutWidget_7 = QtGui.QWidget(self.buttonGroup_6)
        self.layoutWidget_7.setGeometry(QtCore.QRect(7, 30, 251, 28))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.prevButton_8 = QtGui.QPushButton(self.layoutWidget_7)
        self.prevButton_8.setObjectName(_fromUtf8("prevButton_8"))
        self.horizontalLayout_8.addWidget(self.prevButton_8)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.nextButton_8 = QtGui.QPushButton(self.layoutWidget_7)
        self.nextButton_8.setObjectName(_fromUtf8("nextButton_8"))
        self.horizontalLayout_8.addWidget(self.nextButton_8)
        StackedWidget.addWidget(self.authPage)
        self.progressPage = QtGui.QWidget()
        self.progressPage.setObjectName(_fromUtf8("progressPage"))
        self.bannerGroup_7 = QtGui.QGroupBox(self.progressPage)
        self.bannerGroup_7.setGeometry(QtCore.QRect(10, 10, 821, 141))
        self.bannerGroup_7.setObjectName(_fromUtf8("bannerGroup_7"))
        self.bgLabel_9 = QtGui.QLabel(self.bannerGroup_7)
        self.bgLabel_9.setGeometry(QtCore.QRect(10, 30, 811, 81))
        self.bgLabel_9.setStyleSheet(_fromUtf8(""))
        self.bgLabel_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.bgLabel_9.setFrameShadow(QtGui.QFrame.Plain)
        self.bgLabel_9.setText(_fromUtf8(""))
        self.bgLabel_9.setObjectName(_fromUtf8("bgLabel_9"))
        self.mainGroup_7 = QtGui.QGroupBox(self.progressPage)
        self.mainGroup_7.setGeometry(QtCore.QRect(10, 150, 821, 621))
        self.mainGroup_7.setObjectName(_fromUtf8("mainGroup_7"))
        self.loadingLabel = QtGui.QLabel(self.mainGroup_7)
        self.loadingLabel.setGeometry(QtCore.QRect(310, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.loadingLabel.setFont(font)
        self.loadingLabel.setObjectName(_fromUtf8("loadingLabel"))
        self.animatedDial = QtGui.QDial(self.mainGroup_7)
        self.animatedDial.setGeometry(QtCore.QRect(170, 70, 431, 301))
        self.animatedDial.setObjectName(_fromUtf8("animatedDial"))
        self.buttonGroup_7 = QtGui.QGroupBox(self.progressPage)
        self.buttonGroup_7.setGeometry(QtCore.QRect(580, 810, 261, 80))
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.layoutWidget_8 = QtGui.QWidget(self.buttonGroup_7)
        self.layoutWidget_8.setGeometry(QtCore.QRect(7, 30, 251, 28))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.prevButton_9 = QtGui.QPushButton(self.layoutWidget_8)
        self.prevButton_9.setObjectName(_fromUtf8("prevButton_9"))
        self.horizontalLayout_9.addWidget(self.prevButton_9)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.nextButton_9 = QtGui.QPushButton(self.layoutWidget_8)
        self.nextButton_9.setObjectName(_fromUtf8("nextButton_9"))
        self.horizontalLayout_9.addWidget(self.nextButton_9)
        StackedWidget.addWidget(self.progressPage)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget", None))
        self.bannerGroup.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.mainGroup.setTitle(_translate("StackedWidget", "Welcome", None))
        self.buttonGroup.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.prevButton.setText(_translate("StackedWidget", "Previous", None))
        self.nextButton.setText(_translate("StackedWidget", "Next", None))
        self.bannerGroup_2.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.buttonGroup_2.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.prevButton_4.setText(_translate("StackedWidget", "Previous", None))
        self.nextButton_4.setText(_translate("StackedWidget", "Next", None))
        self.mainGroup_2.setTitle(_translate("StackedWidget", "Video", None))
        self.playButton.setText(_translate("StackedWidget", "Play", None))
        self.pauseButton.setText(_translate("StackedWidget", "Pause", None))
        self.stopButton.setText(_translate("StackedWidget", "Stop", None))
        self.bannerGroup_3.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.buttonGroup_3.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.prevButton_5.setText(_translate("StackedWidget", "Previous", None))
        self.nextButton_5.setText(_translate("StackedWidget", "Next", None))
        self.mainGroup_3.setTitle(_translate("StackedWidget", "Banner", None))
        self.textLabel.setText(_translate("StackedWidget", "Add banner text to the video", None))
        self.bannerText.setText(_translate("StackedWidget", "Banner Text", None))
        self.bannerLabel.setText(_translate("StackedWidget", "Banner Text", None))
        self.bannerBtn.setText(_translate("StackedWidget", "Add Banner", None))
        self.previewBtn.setText(_translate("StackedWidget", "Preview ...", None))
        self.fontBtn.setText(_translate("StackedWidget", "Select Font", None))
        self.colorBtn.setText(_translate("StackedWidget", "Set Font Color", None))
        self.bannerGroup_4.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.buttonGroup_4.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.prevButton_6.setText(_translate("StackedWidget", "Previous", None))
        self.nextButton_6.setText(_translate("StackedWidget", "Next", None))
        self.mainGroup_4.setTitle(_translate("StackedWidget", "Timeline", None))
        self.playButton_2.setText(_translate("StackedWidget", "Play", None))
        self.pauseButton_2.setText(_translate("StackedWidget", "Pause", None))
        self.stopButton_2.setText(_translate("StackedWidget", "Stop", None))
        self.startTimeLabel.setText(_translate("StackedWidget", "Start Time", None))
        self.startTimeWidget.setDisplayFormat(_translate("StackedWidget", "h:mm:ss", None))
        self.startTimeLabel_2.setText(_translate("StackedWidget", "End Time", None))
        self.endTimeWidget.setDisplayFormat(_translate("StackedWidget", "h:mm:ss", None))
        self.bannerGroup_5.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.mainGroup_5.setTitle(_translate("StackedWidget", "Tags", None))
        self.seedBox.setTitle(_translate("StackedWidget", "Seed Tag", None))
        self.label.setText(_translate("StackedWidget", "Enter seed tag to generate multiple tags", None))
        self.seedTagBtn.setText(_translate("StackedWidget", "Generate tags", None))
        self.tagsBox.setTitle(_translate("StackedWidget", "Tags", None))
        self.label_2.setText(_translate("StackedWidget", "Comma separated tags. Enter custom tags too", None))
        self.buttonGroup_5.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.prevButton_7.setText(_translate("StackedWidget", "Previous", None))
        self.nextButton_7.setText(_translate("StackedWidget", "Next", None))
        self.bannerGroup_6.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.mainGroup_6.setTitle(_translate("StackedWidget", "Authentication", None))
        self.uploadBox.setTitle(_translate("StackedWidget", "Uploading to video sharing sites", None))
        self.youtubeBtn.setText(_translate("StackedWidget", "Youtube", None))
        self.vimeoBtn.setText(_translate("StackedWidget", "Vimeo", None))
        self.buttonGroup_6.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.prevButton_8.setText(_translate("StackedWidget", "Previous", None))
        self.nextButton_8.setText(_translate("StackedWidget", "Next", None))
        self.bannerGroup_7.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.mainGroup_7.setTitle(_translate("StackedWidget", "Progress", None))
        self.loadingLabel.setText(_translate("StackedWidget", "Processing ...", None))
        self.buttonGroup_7.setTitle(_translate("StackedWidget", "GroupBox", None))
        self.prevButton_9.setText(_translate("StackedWidget", "Previous", None))
        self.nextButton_9.setText(_translate("StackedWidget", "Next", None))

from PyQt4 import phonon

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    StackedWidget = QtGui.QStackedWidget()
    ui = Ui_StackedWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())

